### ISSUE TITLE
In  `VerifySigsAndComputeKeys`, cancel expired keys...

### ISSUE THREAD

**Issue by maxtaco** [keybase/go#88]
This should be done as a last pass.

**Comment by oconnor663** [comment]
chain_link.go:388 VerifySigWithKeyFamily()

**Comment by oconnor663** [comment]
Plan: add an Etime field to ComputedKeyInfo, in the Delegate method

**Comment by oconnor663** [comment]
https://github.com/keybase/go/tree/jack_issue88

**Comment by oconnor663** [comment]
Here's the original commit with Max's comments that I stomped on :p

https://github.com/keybase/go/commit/6fc8da834937af8a652aa8401dc88be8f00d930d

**Comment by oconnor663** [comment]
Ok, the code that's up now does timestamp checking as the sigchain is being verified. After I fix tests, maybe we can get that checked in, and then I can work on a subsequent commit to actually check timestamps for using-keys-now, kind of as part of https://github.com/keybase/go/issues/158.

**Comment by oconnor663** [comment]
TODO: Use BadSigError

**Comment by oconnor663** [comment]
The test failure is because NewComputedKeyInfos is using default ctime/etime values (zero). The right way to get these timestamps:

1) Look at the ctime/etime of ChainLink[0], which always refers to the first key.
2) If the first key is a NaCl key, we're done. If it's PGP (the first few bytes of the key id tell us this), inspect the bundle and pull out the PGP-ctime and PGP-etime. Use these as additional bounds on what's included in the ChainLink.

**Comment by oconnor663** [comment]
^ If the typed chain link is SelfSigChainLink, do that.

If not, check that the link was signed with a PGP key, and that the email address matches your keybase account. Otherwise bail. (Don't need to actually check the signature -- this is done in verifySubchain.)

**Comment by maxtaco** [comment]
Work here is related to #174.  In  #174, the user has an empty sigchain but one PGP key with UID user@keybase.io. 

This is a bug, we should still have an active eldest key in this case.  `verifySubchain` likely needs a tweak.
